function Grad_U = Grad_U_repulsive(R,U_0_alpha_B,r_alpha_B_x,r_alpha_B_y)
%Grad_U_repulsive
%    Grad_U = Grad_U_repulsive(R,U_0_alpha_B,r_alpha_B_x,r_alpha_B_y)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Mar-2023 14:56:33

t2 = abs(r_alpha_B_x);
t3 = abs(r_alpha_B_y);
t6 = 1.0./R;
t4 = t2.^2;
t5 = t3.^2;
t7 = t4+t5;
t8 = sqrt(t7);
t9 = 1.0./t8;
t10 = t6.*t8;
t11 = -t10;
t12 = exp(t11);
Grad_U = [-U_0_alpha_B.*t2.*t6.*t9.*t12.*sign(r_alpha_B_x);-U_0_alpha_B.*t3.*t6.*t9.*t12.*sign(r_alpha_B_y)];
